spring:
    application:
        name: spring-starter
    datasource:
        url: jdbc:postgresql://localhost:5432/library_management_db
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate: 
          ddl-auto: update
        show-sql: true